name = "waiting-list"
main = "index.js"
compatibility_date = "2026-05-06"

[[d1_databases]]
binding = "abuz8_waiting_list"
database_name = "abuz8-waiting-list"
database_id = "8392eb3a-f855-484e-853e-711d036e80c1"
