name = "abuz8-waitlist"
main = "src/index.js"
compatibility_date = "2026-05-01"

routes = [
  { pattern = "waitlist.abuz8ai.com", custom_domain = true }
]

[[d1_databases]]
binding = "DB"
database_name = "abuz8_waitlist"
database_id = "88f3baad-12e9-419f-af4a-9037ae7e7653"

# ADMIN_TOKEN set via: npx wrangler secret put ADMIN_TOKEN
