#!/usr/bin/env python3
"""
scrub-build-comments.py — remove agent/build-process metadata from PUBLIC pages.

WHY THIS EXISTS
---------------
Blog and tool pages were generated by an automation shift that stamped a build
comment into the top of each file, e.g.

    <!-- 2026-08-09 - Weekly content drop (AbuJarvis): ai agent for barbers.
         Net-new slug, existence-checked vs 554 blog files, 0 collisions.
         Dark cinematic theme per site CLAUDE.md ... -->

Those comments are served to the public. Anyone running view-source finds pages
that self-identify as bot output, name an internal agent, name an internal spec
file, and disclose the size of the content library. That is a credibility and
competitive-intel leak, not a rendering bug.

WHAT IT DOES / DOES NOT DO
--------------------------
DOES     : delete HTML comments (and CSS/JS block comments inside <style>/<script>)
           whose text matches a leak pattern.
DOES NOT : touch a single byte outside a comment. Visible copy, markup, meta tags,
           JSON-LD and canonical links are structurally untouchable here.
DOES NOT : remove comments that do not match a leak pattern (layout markers,
           section dividers, conditional comments, licence headers all survive).

SAFETY PROOF (--verify, on by default)
--------------------------------------
For every rewritten file the tool strips ALL comments from the before-text and
from the after-text and asserts the two results are byte-identical. If a scrub
had altered any visible content, that assertion fails and the file is reverted.

Idempotent: running twice is a no-op. Safe to wire into the weekly content shift.

USAGE
-----
    python scripts/scrub-build-comments.py                  # dry run, report only
    python scripts/scrub-build-comments.py --apply          # write changes
    python scripts/scrub-build-comments.py --apply --backup # write + .scrubbak

Exit codes: 0 clean/applied, 1 verification failure, 2 nothing scanned.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys
from datetime import datetime, timezone

# --- what counts as a leak --------------------------------------------------
# Each pattern is matched against COMMENT TEXT ONLY, never against page body.
LEAK_PATTERNS: dict[str, re.Pattern] = {
    "agent_name":      re.compile(r"\bAbuJarvis\b", re.I),
    "agent_alias":     re.compile(r"\bAbuZait\b", re.I),
    "build_cadence":   re.compile(r"weekly content (drop|run)", re.I),
    "internal_spec":   re.compile(r"\bCLAUDE\.md\b"),
    "internal_path":   re.compile(r"[A-Z]:\\+ABU\b"),
    "session_id":      re.compile(r"\bSession [0-9a-f]{8}\b"),
    "library_size":    re.compile(r"existence-checked|\d+\s+blog files|0 collisions", re.I),
    "shift_label":     re.compile(r"\b(morning|afternoon|evening) shift\b", re.I),
    "generated_by":    re.compile(r"generated by (an? )?(AI|agent|Claude|LLM)", re.I),
}

# Comments that must survive even if they trip a pattern (none today; kept as a
# documented escape hatch so a future licence header cannot be eaten silently).
KEEP_PATTERNS: list[re.Pattern] = [
    re.compile(r"^\s*\[if\s", re.I),          # <!--[if IE]> conditional comments
    re.compile(r"copyright|licen[cs]e", re.I),
]

# Directories never served to the public, or not ours to rewrite.
SKIP_DIRS = {
    ".git", ".wrangler", ".claude", "node_modules", "migrations",
    "email-templates", "CONTENT", "scratchpad", "_variants",
}
SKIP_DIR_PREFIXES = ("scratch_", "_bak_", ".")

HTML_COMMENT = re.compile(r"<!--(.*?)-->", re.DOTALL)
BLOCK_COMMENT = re.compile(r"/\*(.*?)\*/", re.DOTALL)

# When a leak comment occupies its own line, take the line's indentation and its
# single trailing newline with it so no orphan blank line is left behind. The
# horizontal whitespace consumed here is why the verifier normalises whitespace
# (see strip_all_comments) instead of comparing raw bytes.
HTML_COMMENT_LINE = re.compile(r"[ \t]*<!--(.*?)-->[ \t]*(\n?)", re.DOTALL)
BLOCK_COMMENT_LINE = re.compile(r"[ \t]*/\*(.*?)\*/[ \t]*(\n?)", re.DOTALL)
_WS = re.compile(r"\s+")


def is_leak(body: str) -> list[str]:
    for keep in KEEP_PATTERNS:
        if keep.search(body):
            return []
    return [name for name, rx in LEAK_PATTERNS.items() if rx.search(body)]


def strip_all_comments(text: str) -> str:
    """Verification normaliser: remove every comment, then collapse whitespace.

    Collapsing whitespace is deliberate. The scrubber is allowed to reclaim the
    indentation and trailing newline of a comment-only line; it is NOT allowed
    to change a single non-whitespace visible byte. Comparing the whitespace-
    normalised, comment-free projections proves exactly that property.
    """
    out = BLOCK_COMMENT.sub(" ", HTML_COMMENT.sub(" ", text))
    return _WS.sub(" ", out).strip()


def scrub(text: str) -> tuple[str, list[str]]:
    """Return (new_text, list_of_leak_kinds_removed)."""
    found: list[str] = []

    def _make(handler_name: str):
        def _sub(m: re.Match) -> str:
            kinds = is_leak(m.group(1))
            if not kinds:
                return m.group(0)
            found.extend(kinds)
            # Keep the newline only when the comment did not own the whole line,
            # i.e. when there is real content before it on that line.
            return ""
        return _sub

    out = HTML_COMMENT_LINE.sub(_make("html"), text)
    out = BLOCK_COMMENT_LINE.sub(_make("block"), out)
    return out, found


def walk(root: str):
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [
            d for d in dirnames
            if d not in SKIP_DIRS and not d.startswith(SKIP_DIR_PREFIXES)
        ]
        for fn in filenames:
            if fn.endswith((".html", ".htm")):
                yield os.path.join(dirpath, fn)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default=".", help="site root (default: cwd)")
    ap.add_argument("--apply", action="store_true", help="write changes to disk")
    ap.add_argument("--backup", action="store_true", help="write .scrubbak alongside")
    ap.add_argument("--report", default="", help="write JSON report to this path")
    args = ap.parse_args()

    scanned = changed = 0
    kinds_total: dict[str, int] = {}
    changed_files: list[dict] = []
    residual: list[dict] = []   # leaks living OUTSIDE comments — human decision
    failures: list[str] = []

    for path in walk(args.root):
        scanned += 1
        try:
            before = open(path, encoding="utf-8", errors="strict").read()
        except (UnicodeDecodeError, OSError) as exc:
            failures.append(f"{path}: unreadable ({exc.__class__.__name__})")
            continue

        after, kinds = scrub(before)

        # Anything still matching a leak pattern after the scrub is in VISIBLE
        # copy. We never rewrite visible copy mechanically — we report it.
        naked = strip_all_comments(after)
        leftover = [n for n, rx in LEAK_PATTERNS.items() if rx.search(naked)]
        if leftover:
            residual.append({"file": os.path.relpath(path, args.root),
                             "kinds": sorted(set(leftover))})

        if after == before:
            continue

        # --- verification: comment-free projections must be identical --------
        if strip_all_comments(before) != strip_all_comments(after):
            failures.append(f"{path}: VERIFY FAILED — visible content would change")
            continue

        changed += 1
        for k in kinds:
            kinds_total[k] = kinds_total.get(k, 0) + 1
        changed_files.append({
            "file": os.path.relpath(path, args.root),
            "kinds": sorted(set(kinds)),
            "bytes_removed": len(before) - len(after),
        })

        if args.apply:
            if args.backup:
                open(path + ".scrubbak", "w", encoding="utf-8").write(before)
            open(path, "w", encoding="utf-8", newline="").write(after)

    mode = "APPLIED" if args.apply else "DRY RUN"
    print(f"[{mode}] scanned {scanned} html files")
    print(f"  files with build-metadata comments : {changed}")
    print(f"  bytes removed                      : {sum(c['bytes_removed'] for c in changed_files):,}")
    for k, v in sorted(kinds_total.items(), key=lambda x: -x[1]):
        print(f"    {k:16} {v}")
    if residual:
        print(f"  ** leaks in VISIBLE copy (not auto-fixed, needs a human): {len(residual)}")
        for r in residual[:20]:
            print(f"     {r['file']}  {r['kinds']}")
    if failures:
        print(f"  ** FAILURES: {len(failures)}")
        for f in failures[:20]:
            print("     " + f)

    if args.report:
        json.dump({
            "generated": datetime.now(timezone.utc).isoformat(),
            "mode": mode, "scanned": scanned, "changed": changed,
            "kinds": kinds_total, "files": changed_files,
            "residual_visible_copy": residual, "failures": failures,
        }, open(args.report, "w"), indent=2)

    if failures:
        return 1
    if scanned == 0:
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
